version: "3.7"

services:
  database:
    container_name: smart-menu-database
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - ./backend/.env
    networks:
      - smart-menu-network
  backend:
    container_name: smart-menu-backend
    build: ./backend
    ports:
      - 3333:3333
    user: node
    environment:
      - DB_HOST=database
      - PORT=3333
    command: bash -c "./wait-for-it.sh database:5432 -- yarn db:sync && yarn seed:run && yarn start"
    depends_on:
      - database
    networks:
      - smart-menu-network
  frontend:
    container_name: smart-menu-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL-http://localhost:3333}
    environment:
      - PORT=80
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    networks:
      - smart-menu-network

networks:
  smart-menu-network:
    driver: bridge

volumes:
  postgres:
